apiVersion: skaffold/v4beta8
kind: Config
deploy:
  kubectl:
    flags:
      apply:
        - "./metric-server/high-availability-1.21+.yaml"
  helm:
    releases:
      - name: "mysql"
        createNamespace: true
        namespace: mysql
        chartPath: "./mysql"
      - name: "redis"
        createNamespace: true
        namespace: redis
        chartPath: "./redis"
      - name: "postgres"
        createNamespace: true
        namespace: postgres
        chartPath: "./postgres"
      - name: "kafka"
        createNamespace: true
        namespace: kafka
        remoteChart: "oci://registry-1.docker.io/bitnamicharts/kafka"
        valuesFiles:
          - ./kafka/values.yaml
