apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - "./metric-server/high-availability-1.21+.yaml"
  helm:
    releases:
      - name: "mysql"
        createNamespace: true
        namespace: mysql
        chartPath: "./mysql"
      - name: "redis"
        createNamespace: true
        namespace: redis
        chartPath: "./redis"
      - name: "postgres"
        createNamespace: true
        namespace: postgres
        chartPath: "./postgres"
