apiVersion: skaffold/v2beta26
kind: Config
deploy:
  helm:
    releases:
      - name: "mysql"
        createNamespace: true
        namespace: mysql
        chartPath: "./mysql"
      - name: "redis"
        createNamespace: true
        namespace: redis
        chartPath: "./redis"
