apiVersion: skaffold/v4beta8
kind: Config
deploy:
  helm:
    releases:
      - name: "mysql"
        createNamespace: true
        namespace: mysql
        chartPath: "./mysql"
      - name: "redis"
        createNamespace: true
        namespace: redis
        chartPath: "./redis"
      - name: "postgres"
        createNamespace: true
        namespace: postgres
        chartPath: "./postgres"
      - name: "kafka"
        createNamespace: true
        namespace: kafka
        remoteChart: "oci://registry-1.docker.io/bitnamicharts/kafka"
        valuesFiles:
          - ./kafka/values.yaml
      - name: "mongo"
        createNamespace: true
        namespace: mongo
        chartPath: "./mongo"
      - name: "metric-server"
        remoteChart: "https://kubernetes-sigs.github.io/metrics-server"
        charPath: "metrics-server/metrics-server"
