apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql.name" . }}-pv
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysql.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.name" . }}-pvc
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
