apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.name" . }}-svc
spec:
  type: LoadBalancer
  selector:
    {{- include "mysql.labels" . | nindent 4 }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.port }}
      protocol: TCP
