apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.name" . }}
spec:
  type: LoadBalancer
  selector:
    {{ include "redis.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.port }}
