apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.name" . }}-pv
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "postgres.name" . }}
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.name" . }}-pvc
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "postgres.name" . }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
