apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.name" . }}-svc
spec:
  type: LoadBalancer
  selector:
    {{- include "postgres.labels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      protocol: TCP
