apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "mongo.namespace" . }}
  name: {{ include "mongo.name" . }}-headless-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "mongo.selectorLabels" . | nindent 4 }}
  ports:
    - name: mongo
      port: {{ .Values.mongo.port }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "mongo.namespace" . }}
  name: {{ include "mongo.name" . }}-0-external-svc
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "mongo.name" . }}-0
  ports:
    - name: mongo
      port: {{ .Values.mongo.port }}
      protocol: TCP
      nodePort: 30010
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "mongo.namespace" . }}
  name: {{ include "mongo.name" . }}-1-external-svc
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "mongo.name" . }}-1
  ports:
    - name: mongo
      port: {{ .Values.mongo.port }}
      protocol: TCP
      nodePort: 30011
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "mongo.namespace" . }}
  name: {{ include "mongo.name" . }}-2-external-svc
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "mongo.name" . }}-2
  ports:
    - name: mongo
      port: {{ .Values.mongo.port }}
      protocol: TCP
      nodePort: 30012
