apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "mongo.namespace" . }}
  name: {{ include "mongo.name" . }}-headless-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "mongo.selectorLabels" . | nindent 4 }}
  ports:
    - name: mongo
      port: {{ .Values.mongo.port }}
      protocol: TCP
{{ $namespace := include "mongo.namespace" . }}
{{ $name := include "mongo.name" . }}
{{ $port := .Values.mongo.port }}
{{ $count := (.Values.mongo.replicaCount | int) }}
{{ range $i := until $count }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $namespace }}
  name: {{ $name }}-{{$i}}-external-svc 
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: {{ $name }}-{{ $i }}
  ports:
    - name: mongo
      port: {{ $port }}
      protocol: TCP
      nodePort: {{ add $i 30010 }}
{{ end }}
