brokers: 1
configurationOverrides:
  "offsets.topic.replication.factor": "1"
prometheus:
  jmx:
    enabled: false
cp-zookeeper:
  enabled: false
  url: "kuckjwi-cluster-zookeeper-cp-zookeeper-headless.kafka.svc.cluster.local:2181"
