apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kuckjwi-connect-cluster
spec:
  version: 3.2.3
  replicas: 1
  bootstrapServers: kuckjwi-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
